Index/urls.py
from django.urls import path
from .views import *

app_name = 'Index'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    # Меню (-Компания-)
    # О нас
    path('company/about/', About.as_view(), name='company-about'),
    # Клиенты
    path('company/clients/', Client.as_view(), name='company-clients'),
    # Вакансии
    path('company/work/', Work.as_view(), name='company-work'),
    # Отзывы
    path('company/review/', Review.as_view(), name='company-review'),
    # Контакты
    path('contacts/', Contact.as_view(), name='contact'),
    # Проекты
    path('projects/', Project.as_view(), name='project'),
    # Политика конфиденциальности
    path('privacy/', Privacy.as_view(), name='privacy'),
    # Меню (-Услуги-)
    # Разработка сайтов
    path('development/', Dev.as_view(), name='service-development'),
    # Интернет магазин
    path('shop/', Shop.as_view(), name='service-shop'),
    # Сложные проекты
    path('complex/', HardProject.as_view(), name='service-complex'),
    # Мобильная разработка
    path('mobile/', MobileDev.as_view(), name='service-mobile'),
    # Поддержка 24/7
    path('support/', Support.as_view(), name='service-support'),
    # Поддержка на 1C-Bitrix24
    path('support-bitrix/', Support1CBitrix24.as_view(), name='service-support-1c-bitrix24'),
    # Интеграция с Bitrix24
    path('bitrix24/', SupportBitrix24.as_view(), name='service-bitrix24'),
    # Продвижение сайтов
    path('seo/', SEO.as_view(), name='service-seo'),
    # Брендинг и айдентика
    path('branding/', Brand.as_view(), name='service-branding'),
    # Обработчик формы
    path('form-get/', form_get)
]

ozseo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Index.urls', namespace='Index'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Index/models.py
from django.db import models


class Work(models.Model):
    title = models.CharField(verbose_name='Заголовок', max_length=100)
    desk = models.TextField(verbose_name='Описание')
    image = models.ImageField(verbose_name='Главное изображение', upload_to='media/')
    image_slug = models.ImageField(verbose_name='Большое Изображение', upload_to='media/')

    class Meta:
        verbose_name = 'Наши работы'
        verbose_name_plural = 'Наши работы'

    def __str__(self):
        return 'Работа: {}'.format(self.title)


class ModelBackForm(models.Model):
    form_text_5 = models.CharField(verbose_name='Имя клиента', max_length=300)
    form_text_18 = models.CharField(verbose_name='Почта клиента', max_length=300)
    form_text_6 = models.CharField(verbose_name='Телефон клиента', max_length=300)
    form_text_7 = models.TextField(verbose_name='Сообщение от клиента')

    class Meta:
        verbose_name = 'Форму обратной связи'
        verbose_name_plural = 'Форма обратной связи'

    def __str__(self):
        return 'Заказ от клиента: ' + self.form_text_5

Index/forms.py
from django.forms import ModelForm

from Index.models import ModelBackForm


class BackForms(ModelForm):
    class Meta:
        model = ModelBackForm
        fields = ['form_text_5', 'form_text_6', 'form_text_18', 'form_text_7']

Index/views.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView

from Index.forms import BackForms


class Index(TemplateView):
    """ Главная страница """
    template_name = 'index/index.html'


# Меню (-Компания-)
class About(TemplateView):
    """ О Нас """
    template_name = 'index/about.html'


class Client(TemplateView):
    """ Клиенты """
    template_name = 'index/client.html'


class Work(TemplateView):
    """ Вакансии """
    template_name = 'index/work.html'


class Review(TemplateView):
    """ Отзывы """
    template_name = 'index/review.html'


class Privacy(TemplateView):
    """ Политика конфиденциальности """
    template_name = 'index/privacy.html'


# Меню (-Услуги-)
class Dev(TemplateView):
    """ Услуги: Разработка сайтов """
    template_name = 'index/services/dev.html'


class Shop(TemplateView):
    """ Услуги: Интернет магазин """
    template_name = 'index/services/online-shop.html'


class HardProject(TemplateView):
    """ Услуги: Сложные проекты """
    template_name = 'index/services/hard-project.html'


class MobileDev(TemplateView):
    """ Услуги: Мобильная разработка """
    template_name = 'index/services/mobile-dev.html'


class Support(TemplateView):
    """ Услуги: Поддержка 24/7 """
    template_name = 'index/services/support.html'


class Support1CBitrix24(TemplateView):
    """ Услуги: Поддержка 1С Bitrix24 """
    template_name = 'index/services/support-1c.html'


class SupportBitrix24(TemplateView):
    """ Услуги: Интеграция Bitrix24 """
    template_name = 'index/services/bitrix24.html'


class SEO(TemplateView):
    """ Услуги: Продвижение сайтов """
    template_name = 'index/services/seo.html'


class Brand(TemplateView):
    """ Услуги: Брендинг и айдентика """
    template_name = 'index/services/brand.html'


# Контакты
class Contact(TemplateView):
    """ Контакты """
    template_name = 'index/contact.html'


# Проекты
class Project(TemplateView):
    """ Проекты """
    template_name = 'index/project.html'


def form_get(request):
    if request.method == "POST":
        form = BackForms(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            redirect('/')
        else:
            print('Проблема какая то: ', form.errors)
    return render(request, 'Index/index.html')

templates/index/client.html
{% extends 'Template/index.html' %}
{% load static %}
{% block name-page %}clients-page{% endblock %}
{% block content %}
    <section class="heading">
        <div class="wrap">
            <ul class="breadcrumbs" itemprop="http://schema.org/breadcrumb" itemscope itemtype="https://schema.org/BreadcrumbList">
                <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
                    <a href="{% url 'Index:index' %}" title="Главная" itemprop="item">
                        <span itemprop="name">Главная</span>
                    </a>
                    <meta itemprop="position" content="1" />
                </li>
                <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
                    <a href="{% url 'Index:company-about' %}" title="Компания" itemprop="item">
                        <span itemprop="name">Компания</span>
                    </a>
                    <meta itemprop="position" content="2" />
                </li>
                <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
                    <span itemprop="name">Наши клиенты</span>
                    <meta itemprop="position" content="3" />
                </li></ul>    </div>
    </section>
    <section class="animate-block custom-header-block">
        <div class="widewrap">
            <div class="row">
                <div class="col-12">
                    <h1 class="heading-1 heading-underline section-title-js">Наши клиенты</h1>
                    <p class="w-100 text text-lh-30 tn_dl_02">Мы работаем с крупнейшими российскими и международными компаниями: с крупнейшими страховыми компаниями, банками, ритейл, автомобильными брендами, государственными проектами, eСommerce, СМИ и другими.</p>
                    <div class="button-case tn_dr_05 tn_dl_04">
                        <a href="#" class="button-blue js-form-have-project">Стать клиентом</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="animate-block-first clients-grid-block">
        <div class="widewrap">
            <div class="row transform-y-55 tn_dl_04 tn_dr_05">
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/clavel.svg' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/gchpinfo.svg' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/kalibr.svg' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/met.svg' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/mirdereva.svg' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/mirdetstva.svg' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/moskonditer.svg' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/osram.svg' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/peresvet.svg' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/ruspetrol.svg' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/vbrr.svg' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/vseinstrumenti.svg' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/showbeep.svg' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/nanofinance.png' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/gazprom.svg' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/rosinfra.svg' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/sanpa.svg' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/galika.svg' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/stroimdom.svg' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/volvo.png' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/cominfro.png' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/centrpartner.png' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/goodcrop.png' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/winfield.png' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/opus.png' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/katrin.png' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/petroltrade.png' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/osnabruk.png' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/melkimbinat.svg' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/gchpsystem.png' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/kapriz.png' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/agrarnijsouz.png' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/vitoms.png' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/marisposa.png' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/electro-express.png' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/jbi1.png' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/garant-stroi.png' %}"></div>
                <div class="clients-grid-block-single"><img alt="" width="" height=""  src="{% static '/local/templates/inetsys/img/logos/transportnie-sistemi.png' %}"></div>
            </div>
        </div>
    </section>


    <section class="animate-block footer-form">
        <div class="wrap">
            <div class="row align-items-start">
                <div class="col-12 col-md-5 col-lg-4 col-xl-5 image-block-before footer-form-block-img"><img alt="" width="" height="" src="{% static '/local/templates/inetsys/img/footer-form-mail.png' %}">
                </div>
                <div class="col-12 col-md-12 col-xl-7 footer-form-block-text">
                    <h3 class="w-100 heading-2 heading-underline text-white section-title-js">Быстрая связь</h3>



                    <form id="bottom-form" class="footer-have-project transform-y-55 tn_dr_05 tn_dl_04 base-form" name="SIMPLE_FORM_3" action="/form-get/" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="form_hidden_16" id="form_hidden_16" value="https://www.inetsys.ru/company/clients/">
                        <input type="hidden" name="g_recaptcha_response" value="">
                        <input type="hidden" name="WEB_FORM_ID" value="3">
                        <input type="hidden" name="sessid" id="sessid_1" value="07471865df1bca654cb950bbffa5caa7" />
                        <div class="input-wrap">
                            <input name="form_text_5" id="form_text_5" type="text" class="input-text required" placeholder="Ваше имя">
                            <label for="form_text_5">Ваше имя <span class="red-star">*</span></label>
                            <span class="input-alert">Укажите ваше имя</span>
                        </div>
                        <div class="input-wrap">
                            <input name="form_text_6" id="form_text_6" type="text" class="input-text phone-validate required" placeholder="Телефон">
                            <label for="form_text_6">Телефон <span class="red-star">*</span></label>
                            <span class="input-alert">Укажите телефон</span>
                        </div>
                        <div class="input-wrap">
                            <input name="form_text_18" id="form_text_18" type="text" class="input-text" placeholder="Email">
                            <label for="form_text_18">Email</label>
                            <span class="input-alert">Укажите Email</span>
                        </div>
                        <div class="input-wrap">
                            <input name="form_text_7" id="form_text_7" type="text" class="input-text required" placeholder="Сообщение">
                            <label for="form_text_7">Сообщение <span class="red-star">*</span></label>
                            <span class="input-alert">Напишите сообщение</span>
                        </div>
                        <p class="text-consent text-consent-checkbox"><input class="styled-checkbox required" type="checkbox" value="1" name="ch1" id="ch1">
                            <label for="ch1"></label> <span> Я согласен с условиями обработки <a href="/privacy/"> персональных данных</a>
              </span>
                            <span class="input-alert input-alert-checkbox">Согласитесь с условиями</span>
                        </p>
                        <button type="submit" name="web_form_submit" class="simple-btn" value="Отправить">Отправить</button>
                    </form>            </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/index/contact.html
{% extends 'Template/index.html' %}
{% load static %}

{% block name-page %}contacts-page background-purple{% endblock %}
{% block content %}

<section class="heading">
    <div class="wrap">
        <ul class="breadcrumbs" itemprop="https://schema.org/breadcrumb" itemscope itemtype="https://schema.org/BreadcrumbList">
            <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
                <a href="{% url 'Index:index' %}" title="Главная" itemprop="item">
                    <span itemprop="name">Главная</span>
                </a>
                <meta itemprop="position" content="1" />
            </li>
            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <span itemprop="name">Контакты</span>
                <meta itemprop="position" content="2" />
            </li></ul>            <h1 class="heading-1 transform-y-55 anim_jump-title-in an_dl_02">Контакты</h1>
    </div>
</section>


<section class="animate-block contacts-block contacts-block-moscow" id="moscow">
    <div class="widewrap" id="bx_3218110189_25">
        <div class="row align-items-start">
            <div class="col-12 col-md-5 col-lg-3 contacts-block-img image-block-before section-title-js">
                <img src="{% static '/upload/iblock/853/853dc0cd582a4b808ea379e43270c671.png' %}" alt="Москва" width="" height="">
            </div>
            <div class="col-12 col-md-7 col-lg-3 contacts-block-info transform-y-55 tn_dr_05 tn_dl_06" itemscope itemtype="https://schema.org/Organization">
                <p class="d-none" itemprop="name">Интернет-системы</p>
                <p class="heading-3">
                    Москва                </p>
                <div class="contacts-adres" itemprop="address" itemscope itemtype="https://schema.org/PostalAddress">
                    <p class="d-none" itemprop="addressLocality">Москва</p>
                    <span itemprop="streetAddress">ул. Смольная, д 24а, офис&nbsp;1811</span>
                </div>
                <a class="contacts-phone" href="tel:'+7 (495) 724-90-65'" itemprop="telephone">+7 (495) 724-90-65</a>
                <p class="contacts-hours">
                    Пн - пт. 9:00 - 19:00                </p>
                <a class="contacts-mail" href="mailto:sales@inetsys.ru" itemprop="email">sales@inetsys.ru</a>
                <a href="#/" class="contacts-map arrow-button" data-region="tver" >На большую карту</a>
            </div>
            <div id="map25" class="col-12 col-lg-6 contacts-block-map">
            </div>
        </div>
    </div>
</section>
<section class="animate-block contacts-block contacts-block-tver" id="tver">
    <div class="widewrap" id="bx_3218110189_26">
        <div class="row align-items-start">
            <div class="col-12 col-md-5 col-lg-3 contacts-block-img image-block-before section-title-js">
                <img src="{% static '/upload/iblock/80c/80c9d8568001ae5a334bdd60633f22d1.png' %}" alt="Тверь" width="" height="">
            </div>
            <div class="col-12 col-md-7 col-lg-3 contacts-block-info transform-y-55 tn_dr_05 tn_dl_06" itemscope itemtype="https://schema.org/Organization">
                <p class="d-none" itemprop="name">Интернет-системы</p>
                <p class="heading-3">
                    Тверь                </p>
                <div class="contacts-adres" itemprop="address" itemscope itemtype="https://schema.org/PostalAddress">
                    <p class="d-none" itemprop="addressLocality">Тверь</p>
                    <span itemprop="streetAddress">пр-т Победы, д.3, офис&nbsp;313</span>
                </div>
                <a class="contacts-phone" href="tel:'+7 (4822) 34-55-73'" itemprop="telephone">+7 (4822) 34-55-73</a>
                <p class="contacts-hours">
                    Пн - пт. 9:00 - 19:00                </p>
                <a class="contacts-mail" href="mailto:sales@inetsys.ru" itemprop="email">sales@inetsys.ru</a>                 <a href="#" class="contacts-map arrow-button" data-region="tver" >На большую карту</a>
            </div>
            <div id="map26" class="col-12 col-lg-6 contacts-block-map">
            </div>
        </div>
    </div>
</section>


<section class="animate-block footer-form">
    <div class="wrap">
        <div class="row align-items-start">
            <div class="col-12 col-md-5 col-lg-4 col-xl-5 image-block-before footer-form-block-img">
                <img alt="" width="" height="" src="{% static '/local/templates/inetsys/img/footer-form-mail.png' %}">
            </div>
            <div class="col-12 col-md-12 col-xl-7 footer-form-block-text">
                <h3 class="w-100 heading-2 heading-underline text-white section-title-js">Быстрая связь</h3>



                <form id="bottom-form" class="footer-have-project transform-y-55 tn_dr_05 tn_dl_04 base-form" name="SIMPLE_FORM_3" action="/form-get/" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" name="form_hidden_16" id="form_hidden_16" value="https://www.inetsys.ru/contacts/">
                    <input type="hidden" name="g_recaptcha_response" value="">
                    <input type="hidden" name="WEB_FORM_ID" value="3">
                    <input type="hidden" name="sessid" id="sessid_1" value="07471865df1bca654cb950bbffa5caa7" />
                    <div class="input-wrap">
                        <input name="form_text_5" id="form_text_5" type="text" class="input-text required" placeholder="Ваше имя">
                        <label for="form_text_5">Ваше имя <span class="red-star">*</span></label>
                        <span class="input-alert">Укажите ваше имя</span>
                    </div>
                    <div class="input-wrap">
                        <input name="form_text_6" id="form_text_6" type="text" class="input-text phone-validate required" placeholder="Телефон">
                        <label for="form_text_6">Телефон <span class="red-star">*</span></label>
                        <span class="input-alert">Укажите телефон</span>
                    </div>
                    <div class="input-wrap">
                        <input name="form_text_18" id="form_text_18" type="text" class="input-text" placeholder="Email">
                        <label for="form_text_18">Email</label>
                        <span class="input-alert">Укажите Email</span>
                    </div>
                    <div class="input-wrap">
                        <input name="form_text_7" id="form_text_7" type="text" class="input-text required" placeholder="Сообщение">
                        <label for="form_text_7">Сообщение <span class="red-star">*</span></label>
                        <span class="input-alert">Напишите сообщение</span>
                    </div>
                    <p class="text-consent text-consent-checkbox"><input class="styled-checkbox required" type="checkbox" value="1" name="ch1" id="ch1">
                        <label for="ch1"></label> <span> Я согласен с условиями обработки <a href="/privacy/"> персональных данных</a></span>
                        <span class="input-alert input-alert-checkbox">Согласитесь с условиями</span>
                    </p>
                    <button type="submit" name="web_form_submit" class="simple-btn" value="Отправить">Отправить</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}